spring:
  ai:
    openai:
      api-key: ${API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
      image:
        options:
          model: dall-e-3
  datasource:
    url: jdbc:postgresql://localhost:5432/embedding
    username:
    password: